# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#

---

dontChroot: false

timeout: 999

script:
    - "-rm ${ROOT}/etc/sudoers.d/g_wheel"
    - "-rm -rf ${ROOT}/etc/mkinitcpio.conf.d"
    - "-rm -r ${ROOT}/etc/systemd/system/getty@tty1.service.d"
    - "-rm -r ${ROOT}/etc/systemd/system/multi-user.target.wants/pacman-init.service"
    - "-rm -r ${ROOT}/etc/systemd/system/pacman-init.service"
    - "-rm ${ROOT}/etc/systemd/system/etc-pacman.d-gnupg.mount"
    - "-rm ${ROOT}/root/.zlogin"
    - "-rm ${ROOT}/etc/polkit-1/rules.d/49-nopasswd_global.rules"
    - "-rm ${ROOT}/etc/polkit-1/rules.d/49-nopasswd-calamares.rules"
    - "-rm ${ROOT}/etc/gdm/custom.conf"
    - "-rm ${ROOT}/etc/motd"
    - "-rm -rf ${ROOT}/etc/dconf/db/local.d/00-logout"
    - "-rm -rf ${ROOT}/etc/dconf/db/local.d/06-disableoverviewinstallation"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/bssh.desktop"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/avahi-discover.desktop"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/qv4l2.desktop"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/qvidcap.desktop"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/stoken-gui.desktop"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/stoken-gui-small.desktop"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/vim.desktop"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/lftp.desktop"
    - "-echo -e Hidden=true >> ${ROOT}/usr/share/applications/bvnc.desktop"
    - "-systemctl enable sddm"
    - "-systemctl enable bluetooth"
    - "-bootctl install"
    - "-mkdir -p /boot/loader/entries"
    - "-chmod +x /etc/calamares/scripts/bootloader"
    - "-bash /etc/calamares/scripts/bootloader"
    - "-mv ${ROOT}/etc/skel/.zshrc_postinstall ${ROOT}/etc/skel/.zshrc"
    - "-mv ${ROOT}/etc/os-release ${ROOT}/usr/lib/os-release"
    - "-ln -s ${ROOT}/usr/lib/os-release ${ROOT}/etc/os-release"
    - "-mv ${ROOT}/etc/mkinitcpio.d/linux-postinstall.preset ${ROOT}/etc/mkinitcpio.d/linux.preset"
    - "-rm -rf ${ROOT}/usr/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm"
    - "-mv ${ROOT}/usr/share/plymouth/themes/spinner/watermark-postinstall.png ${ROOT}/usr/share/plymouth/themes/spinner/watermark.png"
    - "-${ROOT}/etc/calamares/scripts/remove-ucode"
    - "-chmod +x ${ROOT}/usr/bin/bsod"
    - "-chmod +x ${ROOT}/usr/local/bin/rum"
    - "-chmod +x ${ROOT}/usr/bin/photo"
    - "-chmod +x ${ROOT}/usr/bin/designer"
    - "-chmod +x ${ROOT}/usr/bin/publisher"
    - "-chmod 755 ${ROOT}/usr/share/gnome-shell/extensions -R"
    - "-dconf update"
    - "-amixer set 'Master' 100%"
    - "-alsactl store"
    - "-pacman -Syu --noconfirm"
    - "-pacman -R totem --noconfirm"
    - "-pacman -R archinstall --noconfirm"

